export { default as ExpressoTradicional } from './Expresso.svg'
export { default as Americano } from './Americano.svg'
export { default as CafeComLeite } from './Café com Leite.svg'
export { default as CafeGelado } from './Café Gelado.svg'
export { default as Arabe } from './Árabe.svg'
export { default as Cappuccino } from './Capuccino.svg'
export { default as ChocolateQuente } from './Chocolate Quente.svg'
export { default as Cubano } from './Cubano.svg'
export { default as ExpressoCremoso } from './Expresso Cremoso.svg'
export { default as Havaiano } from './Havaiano.svg'
export { default as Irlandes } from './Irlandês.svg'
export { default as Latte } from './Latte.svg'
export { default as Macchiato } from './Macchiato.svg'
export { default as Mocha } from './Mochaccino.svg'
