import type { Metadata } from 'next'
import { Roboto, Baloo_2 as Baloo2 } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { CartProvider } from '@/context/CartContext'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '700'], // ajuste os pesos conforme necessário
})

const baloo = Baloo2({
  subsets: ['latin'],
  variable: '--font-baloo',
  weight: ['700', '800'],
})

export const metadata: Metadata = {
  title: 'Coffee Delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${baloo.variable}`}>
      <body className={`antialiased`}>
        <CartProvider>
          <div className="font-roboto mx-auto min-h-screen w-360 px-40">
            <Header />
            <main>{children}</main>
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
